-- 코드를 작성해주세요
SELECT
    ROUND(AVG(COALESCE(LENGTH, 10)),2) AS AVERAGE_LENGTH
FROM
    FISH_INFO
    
    
# COALESCE(LENGTH, 10)
# LENGTH가 NULL이면 10으로 처리 / NULL이 아니면 그대로 사용함
# CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END 와 같은 의미임