-- 코드를 입력하세요
# ROUND(평균, 1) - 소수점 두 번째 자리에서 반올림(=소수점 첫째 자리까지 반올림)
# 정수 / 정수 = 정수 결과 나옴
# 평균, 비율 계산할 때는 실수화 먼저 진행!!
SELECT CAR_ID,
    ROUND(SUM(DATEDIFF(END_DATE, START_DATE) + 1) * 1.0 / COUNT(*) , 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING SUM(DATEDIFF(END_DATE, START_DATE) + 1) * 1.0 / COUNT(*) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

# SUM(DATEDIFF(END_DATE, START_DATE) + 1) * 1.0 / COUNT(*)
# CAST(SUM(DATEDIFF(END_DATE, START_DATE) + 1) AS DOUBLE) / COUNT(*)
