-- 코드를 입력하세요
# 보호소에 들어왔지만, 입양 못 간 애들
# INS O , OUTS X 중에서 가장 오래 있던 애들 3마리
SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AI
LEFT JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.ANIMAL_ID IS NULL
ORDER BY AI.DATETIME # 보호시작일 순
LIMIT 3
