-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
# LIKE '%03%' 03이 포함 / LIKE '03%' 03으로 시작 / LIKE '%03' 03으로 끝남
# IS NULL / IS NOT NULL 
WHERE DATE_OF_BIRTH LIKE '%03%'
    AND GENDER = 'W'
    AND TLNO IS NOT NULL
ORDER BY MEMBER_ID

# SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
# FROM MEMBER_PROFILE
# WHERE MONTH(DATE_OF_BIRTH) = 3
#     AND GENDER = 'W'
#     AND TLNO IS NOT NULL
# ORDER BY MEMBER_ID