-- 코드를 작성해주세요

# Join 방식
# SELECT COUNT(*) AS FISH_COUNT
# FROM FISH_INFO FI
# JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE
# WHERE FN.FISH_NAME = 'BASS' OR FN.FISH_NAME = 'SNAPPER'


# 서브쿼리 방식 사용해보자
# 1. 이름이 BASS, SNAPPER인 물고기의 FISH_TYPE
# SELECT FISH_TYPE
# FROM FISH_NAME_INFO
# WHERE FISH_NAME IN ('BASS', 'SNAPPER')

# 2. 작성한 서브쿼리를 큰 쿼리 안에 집어넣음
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE IN (
  SELECT FISH_TYPE
  FROM FISH_NAME_INFO
  WHERE FISH_NAME IN ('BASS', 'SNAPPER')
)