-- 코드를 입력하세요
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE PUBLISHED_DATE LIKE '2021%' 
  AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;

# 2021-10-24 00:00:00 이거를 2021-10-24 나오도록 바꿔야 함!
# 그럼 SELECT절에서 형식만 맞춰주면 됨!
# DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE 값을 YYYY-MM-DD 형식으로 VARCHAR 타입으로 변환